; ST7735 TFT LCD 显示测试
[env:esp32dev]
platform        = espressif32
board           = esp32-s3-devkitc-1
framework       = arduino
monitor_speed   = 115200
lib_deps =
    file://../../common/TFT_eSPI
build_flags =
