; ============================================================
;  城市公园环境监测系统 — 子节点
;  PlatformIO 配置 (VS Code)
; ============================================================

[env:esp32dev]
platform        = espressif32
board           = esp32dev
framework       = arduino
monitor_speed   = 115200
upload_speed    = 921600

; 依赖库
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14

; 编译选项
build_flags =
    -D CORE_DEBUG_LEVEL=2
    -I ../common
